// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingSystem.DAL;

namespace TradingSystem.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20210530123151_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("TradingSystem.Business.Delivery.DeliveryStatus", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("PackageId");

                    b.ToTable("deliveryStatuses");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Address", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApartmentNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.Property<string>("_state")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("nameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Storesid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Storesid1")
                        .HasColumnType("TEXT");

                    b.Property<string>("_name")
                        .HasColumnType("TEXT");

                    b.Property<double>("_price")
                        .HasColumnType("REAL");

                    b.Property<int>("_quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_storeName")
                        .HasColumnType("TEXT");

                    b.Property<double>("_weight")
                        .HasColumnType("REAL");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("Storesid");

                    b.HasIndex("Storesid1");

                    b.ToTable("products");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.PurchasePolicy", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("PurchasePolicy");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.ShoppingBasket", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingCartusername")
                        .HasColumnType("TEXT");

                    b.Property<string>("shoppingCartusername")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("storesid")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ShoppingCartusername");

                    b.HasIndex("shoppingCartusername");

                    b.HasIndex("storesid");

                    b.ToTable("membersShoppingBaskets");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.ShoppingCart", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("username");

                    b.ToTable("membersShoppingCarts");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.State", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("username");

                    b.ToTable("states");

                    b.HasDiscriminator<string>("Discriminator").HasValue("State");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Statuses.PurchasedProduct", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductHistoryDataid")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ProductHistoryDataid");

                    b.ToTable("purchasedProducts");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Store", b =>
                {
                    b.Property<Guid>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("_addressid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("foundersid")
                        .HasColumnType("TEXT");

                    b.Property<string>("founderusername")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("purchasePolicyid")
                        .HasColumnType("TEXT");

                    b.HasKey("sid");

                    b.HasIndex("_addressid");

                    b.HasIndex("purchasePolicyid");

                    b.HasIndex("foundersid", "founderusername");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StorePackage.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Appointersid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Appointerusername")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Appointersid", "Appointerusername");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Appointer", b =>
                {
                    b.Property<Guid>("sid")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("musername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("sid", "username");

                    b.HasIndex("musername");

                    b.ToTable("appointers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Appointer");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Manager", b =>
                {
                    b.Property<Guid>("sid")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("musername")
                        .HasColumnType("TEXT");

                    b.HasKey("sid", "username");

                    b.HasIndex("musername");

                    b.HasIndex("username");

                    b.ToTable("managers");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Prem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Managersid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Managerusername")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PurchasePolicyid")
                        .HasColumnType("TEXT");

                    b.Property<string>("p")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("PurchasePolicyid");

                    b.HasIndex("Managersid", "Managerusername");

                    b.ToTable("Prem");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.TransactionStatus", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("_deliveryStatusPackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("_paymentStatusPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("_status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("productHistoriesid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("storeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("_deliveryStatusPackageId");

                    b.HasIndex("_paymentStatusPaymentId");

                    b.HasIndex("productHistoriesid");

                    b.ToTable("transactionStatuses");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.UserPackage.ProductInCart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShoppingBasketid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShoppingBasketid1")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("productid")
                        .HasColumnType("TEXT");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ShoppingBasketid");

                    b.HasIndex("ShoppingBasketid1");

                    b.HasIndex("productid");

                    b.ToTable("productInCarts");
                });

            modelBuilder.Entity("TradingSystem.Business.Payment.PaymentStatus", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentId");

                    b.ToTable("paymentStatuses");
                });

            modelBuilder.Entity("TradingSystem.Business.ProductHistoryData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("productHistoryDatas");
                });

            modelBuilder.Entity("TradingSystem.Business.UserManagement.DataUser", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLoggedin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.HasKey("username");

                    b.ToTable("dataUsers");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.MemberState", b =>
                {
                    b.HasBaseType("TradingSystem.Business.Market.State");

                    b.HasDiscriminator().HasValue("MemberState");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Founder", b =>
                {
                    b.HasBaseType("TradingSystem.Business.Market.StoreStates.Appointer");

                    b.HasIndex("sid")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Founder");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Owner", b =>
                {
                    b.HasBaseType("TradingSystem.Business.Market.StoreStates.Appointer");

                    b.Property<Guid?>("sid1")
                        .HasColumnType("TEXT");

                    b.HasIndex("sid1");

                    b.HasIndex("username");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.AdministratorState", b =>
                {
                    b.HasBaseType("TradingSystem.Business.Market.MemberState");

                    b.HasDiscriminator().HasValue("AdministratorState");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Product", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.Category", null)
                        .WithMany("products")
                        .HasForeignKey("CategoryName");

                    b.HasOne("TradingSystem.Business.Market.Store", null)
                        .WithMany("_products")
                        .HasForeignKey("Storesid");

                    b.HasOne("TradingSystem.Business.Market.Store", null)
                        .WithMany("Products")
                        .HasForeignKey("Storesid1");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.ShoppingBasket", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.ShoppingCart", null)
                        .WithMany("ShoppingBaskets")
                        .HasForeignKey("ShoppingCartusername");

                    b.HasOne("TradingSystem.Business.Market.ShoppingCart", "shoppingCart")
                        .WithMany("shoppingBaskets")
                        .HasForeignKey("shoppingCartusername");

                    b.HasOne("TradingSystem.Business.Market.Store", "store")
                        .WithMany()
                        .HasForeignKey("storesid");

                    b.Navigation("shoppingCart");

                    b.Navigation("store");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Statuses.PurchasedProduct", b =>
                {
                    b.HasOne("TradingSystem.Business.ProductHistoryData", null)
                        .WithMany("productId_quantity")
                        .HasForeignKey("ProductHistoryDataid");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Store", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.Address", "_address")
                        .WithMany()
                        .HasForeignKey("_addressid");

                    b.HasOne("TradingSystem.Business.Market.PurchasePolicy", "purchasePolicy")
                        .WithMany()
                        .HasForeignKey("purchasePolicyid");

                    b.HasOne("TradingSystem.Business.Market.StoreStates.Founder", "founder")
                        .WithMany()
                        .HasForeignKey("foundersid", "founderusername");

                    b.Navigation("_address");

                    b.Navigation("founder");

                    b.Navigation("purchasePolicy");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StorePackage.Bid", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.StoreStates.Appointer", null)
                        .WithMany("Bids")
                        .HasForeignKey("Appointersid", "Appointerusername");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Appointer", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.MemberState", "m")
                        .WithMany()
                        .HasForeignKey("musername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("m");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Manager", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.MemberState", "m")
                        .WithMany()
                        .HasForeignKey("musername");

                    b.HasOne("TradingSystem.Business.Market.Store", "s")
                        .WithMany("managers")
                        .HasForeignKey("sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingSystem.Business.Market.MemberState", "appointer")
                        .WithMany()
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appointer");

                    b.Navigation("m");

                    b.Navigation("s");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Prem", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.PurchasePolicy", null)
                        .WithMany("availablePurchaseKinds")
                        .HasForeignKey("PurchasePolicyid");

                    b.HasOne("TradingSystem.Business.Market.StoreStates.Manager", null)
                        .WithMany("store_permission")
                        .HasForeignKey("Managersid", "Managerusername");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.TransactionStatus", b =>
                {
                    b.HasOne("TradingSystem.Business.Delivery.DeliveryStatus", "_deliveryStatus")
                        .WithMany()
                        .HasForeignKey("_deliveryStatusPackageId");

                    b.HasOne("TradingSystem.Business.Payment.PaymentStatus", "_paymentStatus")
                        .WithMany()
                        .HasForeignKey("_paymentStatusPaymentId");

                    b.HasOne("TradingSystem.Business.ProductHistoryData", "productHistories")
                        .WithMany()
                        .HasForeignKey("productHistoriesid");

                    b.Navigation("_deliveryStatus");

                    b.Navigation("_paymentStatus");

                    b.Navigation("productHistories");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.UserPackage.ProductInCart", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.ShoppingBasket", null)
                        .WithMany("_product_quantity")
                        .HasForeignKey("ShoppingBasketid");

                    b.HasOne("TradingSystem.Business.Market.ShoppingBasket", null)
                        .WithMany("Product_quantity")
                        .HasForeignKey("ShoppingBasketid1");

                    b.HasOne("TradingSystem.Business.Market.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid");

                    b.Navigation("product");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Founder", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.Store", "s")
                        .WithOne()
                        .HasForeignKey("TradingSystem.Business.Market.StoreStates.Founder", "sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("s");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Owner", b =>
                {
                    b.HasOne("TradingSystem.Business.Market.Store", "s")
                        .WithMany("owners")
                        .HasForeignKey("sid1");

                    b.HasOne("TradingSystem.Business.Market.MemberState", "appointer")
                        .WithMany()
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appointer");

                    b.Navigation("s");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.PurchasePolicy", b =>
                {
                    b.Navigation("availablePurchaseKinds");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.ShoppingBasket", b =>
                {
                    b.Navigation("_product_quantity");

                    b.Navigation("Product_quantity");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.ShoppingCart", b =>
                {
                    b.Navigation("shoppingBaskets");

                    b.Navigation("ShoppingBaskets");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.Store", b =>
                {
                    b.Navigation("_products");

                    b.Navigation("managers");

                    b.Navigation("owners");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Appointer", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("TradingSystem.Business.Market.StoreStates.Manager", b =>
                {
                    b.Navigation("store_permission");
                });

            modelBuilder.Entity("TradingSystem.Business.ProductHistoryData", b =>
                {
                    b.Navigation("productId_quantity");
                });
#pragma warning restore 612, 618
        }
    }
}
